using JobPortal.Domain.Enums;
using JobPortal.Shared.Models;

namespace JobPortal.Application.Features.Jobs;

public sealed record CreateJobRequest(string Title, string Description, Guid CompanyId, Guid CategoryId, string ApplicationUrl, string? Responsibilities, string? Requirements, string? Benefits, string? Location, decimal? MinimumSalary, decimal? MaximumSalary, string CurrencyCode, EmploymentType EmploymentType, WorkplaceType WorkplaceType, ExperienceLevel ExperienceLevel, DateTime? ExpiresAtUtc);
public sealed record UpdateJobRequest(string Title, string Description, Guid CompanyId, Guid CategoryId, string ApplicationUrl, string? Responsibilities, string? Requirements, string? Benefits, string? Location, decimal? MinimumSalary, decimal? MaximumSalary, string CurrencyCode, EmploymentType EmploymentType, WorkplaceType WorkplaceType, ExperienceLevel ExperienceLevel, DateTime? ExpiresAtUtc);
public sealed record JobSearchQuery(int PageNumber = 1, int PageSize = 20, string? Search = null, Guid? CompanyId = null, Guid? CategoryId = null, JobStatus? Status = null, EmploymentType? EmploymentType = null, WorkplaceType? WorkplaceType = null, ExperienceLevel? ExperienceLevel = null, bool? IsFeatured = null, bool? IsHidden = null, bool? IsDeleted = false, DateTime? PublishedFromUtc = null, DateTime? PublishedToUtc = null, string SortBy = "createdAt", string SortDirection = "desc", DateTime? ExpiresFromUtc = null, DateTime? ExpiresToUtc = null);
public sealed record JobResponse(Guid Id, string ReferenceNumber, string Title, string Slug, string Description, string? Responsibilities, string? Requirements, string? Benefits, string ApplicationUrl, string CompanyName, Guid CompanyId, string CategoryName, Guid CategoryId, string? Location, decimal? MinimumSalary, decimal? MaximumSalary, string CurrencyCode, EmploymentType EmploymentType, WorkplaceType WorkplaceType, ExperienceLevel ExperienceLevel, JobStatus Status, bool IsFeatured, bool IsHidden, DateTime? PublishedAtUtc, DateTime? ExpiresAtUtc, DateTime CreatedAtUtc, DateTime? UpdatedAtUtc, bool IsDeleted, DateTime? DeletedAtUtc);
